- package-lock.json
- package.json
- src/App.test.tsx
- src/components/MenuItem/index.test.tsx
- src/components/MenuItem/index.tsx
- src/components/NavigationBar/index.test.tsx
- src/components/NavigationBar/index.tsx
- src/components/NavigationMenu/index.test.tsx
- src/components/NavigationMenu/index.tsx
- src/index.tsx
- src/setupTests.ts
- src/test-utils/TestWrapper.tsx
- tsconfig.json
Added unit test for menu item component 
- testing that component renders with props passed to it for text-Setting, highlighter, overlay-tint, hide-Images and line-focus.
- it also checks the total children the component contains.
> unit test for menu item component

- src/components/MenuItem/index.tsx
- src/components/NavigationBar/index.test.tsx
Changes 
refactored css: removed the text-decoration from the links in menu item
> created new branch and refactored css for menu item links

- src/components/Toggle/index.test.tsx
- src/components/Toggle/index.tsx
- src/pages/OverlayTint/index.test.tsx
- src/pages/OverlayTint/index.tsx
#27 
- Created a toggle component (the ui will be refined by @t-divya in another PR)
- Used the toggle component in the overlay screen
- Minor UI adjustments
> 27 - Created a toggle/checkbox component

- src/components/InnerTextSettingPage/DropDownFontText/index.test.tsx
- src/components/InnerTextSettingPage/DropDownFontText/index.tsx
Includes unit test on drop down font text menu.
Test mocks a function using jest.fn():
- It test if the onchange function calls the changeText function(default import).
> Test drop down font text

- public/css/index.css
- public/manifest.json
- public/scripts/background.js
- public/scripts/content.js
- Added background script
- Added content script
- Display of overlay using content script and enable disable
> 31 - refactor overlay enable/disable actions

- public/css/index.css
- public/scripts/content.js
- src/pages/OverlayTint/index.test.tsx
- src/pages/OverlayTint/index.tsx
#36 
- fix: display the overlay when the overlay is enabled back
- Allow user to change the color of the overlay
> 36 - Set overlay color

- public/scripts/content.js
- src/components/DropDown/index.test.tsx
- src/components/DropDown/index.tsx
- src/pages/OverlayTint/index.test.tsx
- src/pages/TextSettings/index.test.tsx
- src/pages/TextSettings/index.tsx
- src/storage/StoreContext/index.test.tsx
- src/storage/StoreContext/index.ts
- src/storage/chrome-storage/index.test.ts
- src/storage/chrome-storage/index.ts
#3 
- Created a new dropdown
- Save the font changes to storage
- Added component panel
> 3 - Added font family settings

- contents/Overlay/styles.css
- popup/App.tsx
- popup/components/NavigationBar/index.tsx
- popup/pages/Home/index.tsx
- Refactored the navigation menu to display back button 
- go back in history once the back button is clicked
> feat: implemented back button

- contents/TextStyles.ts
- popup/components/NavigationMenu/index.tsx
- popup/pages/LineFocus/index.tsx
- popup/storage/StoreContext/index.ts
- popup/storage/chrome-storage/index.ts
> updated the ui and state for LineFocus

- .github/workflows/main.yml
#59 
- Updated the build pipeline to build the project on each commit
> 59 - build pipeline

- babel.config.js
- contents/LineFocus.tsx
- contents/Overlay.tsx
- e2e/bootstrap.ts
- e2e/constants.ts
- e2e/launch.test.ts
- e2e/test-pages/basic-page.html
- e2e/testers/HomePageTesters.ts
- e2e/testers/LineFocusPageTesters.ts
- e2e/testers/OverlayPageTesters.ts
- e2e/testers/TextSettingsTesters.ts
- e2e/types/index.ts
- e2e/utils.ts
- e2e/utils/index.ts
- package-lock.json
- package.json
- popup/components/ColorPicker/index.tsx
- popup/components/DropDown/index.tsx
- popup/components/MenuItem/index.tsx
- popup/components/NavigationBar/index.tsx
- popup/components/NavigationMenu/index.tsx
- popup/pages/LineFocus/index.tsx
- popup/pages/OverlayTint/index.tsx
- popup/pages/TextSettings/index.tsx
> 64 automated testing puppeteer

- popup/pages/LineFocus/index.tsx
> fix: updated the focus change issue

- contents/LineFocus.tsx
> fixed: the moving of the line focus and limit the movement to just the screen

- popup/constants/colorsList.ts
- popup/storage/chrome-storage/index.ts
> fix: fixed the initial state values so that user can just go and enable the features

- popup/App.tsx
- popup/chrome-utils/tabs.ts
- popup/components/NavigationBar/index.tsx
- popup/components/NavigationMenu/index.tsx
- popup/pages/Home/index.tsx
- popup/pages/TextSettings/index.tsx
#74 
#78 
- Added a refresh link since it is noticed in some cases the changes are not applied
- Updated background to be consistent in all pages
> feat: added the refresh link and fixed bg issue

- popup/components/ColorPicker/index.tsx
- popup/pages/TextSettings/index.tsx
- popup/storage/StoreContext/index.ts
- popup/storage/chrome-storage/index.ts
> feat: user should be able to choose default color and change the font

- popup/components/ColorPicker/index.tsx
> feat: added default color selection

- contents/LineFocus.tsx
- popup/pages/LineFocus/index.tsx
#94 
Refactored the moving logic to be smoother
> 94 - line focus fix

- popup/storage/chrome-storage/index.ts
> chore: updated the default height for line focus

- popup/App.css
- popup/App.tsx
- popup/storage/chrome-storage/index.ts
#104 
- Updated popup font on font change
- Display spinner while loading the storage
> 104 - Apply selected font to plugin popup

- contents/TextToSpeech.ts
#113 
- Created a new content script to enable the text to speech on text selection
> feat: client side script to enable text to speech

- popup/App.tsx
- popup/components/NavigationBar/index.tsx
- popup/components/NavigationMenu/index.tsx
- popup/pages/OverlayTint/index.tsx
- popup/pages/TextToSpeech/index.tsx
- popup/storage/StoreContext/index.ts
- popup/storage/chrome-storage/index.ts
#112 
- Added menu item for Text To Speech
- Added Text To Speech Settings Page
- Added enabled, pitch, rate and volume but not voice setting.
> 112 text to speech component

- contents/TextToSpeech.ts
- package.json
- popup/components/DropDown/index.tsx
- popup/pages/OverlayTint/index.tsx
- popup/pages/TextToSpeech/index.tsx
- popup/storage/StoreContext/index.ts
- popup/storage/chrome-storage/index.ts
121
- Added voice list that provides different voices 
- Added changes to content script
screenshots
> added different voice in tts

- popup/App.tsx
#126 
- Fixed bottom area that had extra white space 
- Added overflow property to app
screentshot
> chore: fixed bottom area to have uniform background

- popup/components/NavigationBar/index.tsx
#133 
- hidden disable button once the user disables the setting and visible when user enables any setting
> 133-hide disable button when settings are not enabled

- popup/components/NavigationBar/index.tsx
- popup/pages/LineFocus/index.tsx
- popup/pages/OverlayTint/index.tsx
- popup/pages/TextToSpeech/index.tsx
#125 
- Added property on slider that shows value as slider moves.
> 125 indicate value on slider move
